version: "3"

services:
  postgresDb:
    image: postgres:10
    container_name: postgresTrip
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - "./data/postgres:/var/lib/postgresql/data/"
    ports:
      - 5429:5432
    environment:
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-password
      - PGTZ=GMT+3
      - DEBUG=true
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminTrip
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@trip
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 5050:80
      - 443:443
    depends_on:
      - postgresDb
